name = "euler_tools"
description = "Mathematical functions and tools to solve Project Euler problems."
version = "0.1.2-dev"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]
[[depends-on]]
aunit = "^23.0.0"
