name = "euler_tools"
description = "Assortment of mathematical functions to solve Project Euler problems."
version = "1.0.0"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]
