name = "euler_tools"
description = "Assortment of mathematical functions to solve Project Euler problems."
version = "1.0.2"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]
licenses = "MIT"
tags = ["project-euler", "mathematics"]
website = "https://github.com/rocher/euler_tools"
project-files = ["euler_tools.gpr", "tests/euler_tools_tests.gpr"]
[[depends-on]]
gnat = ">=2021 | (>=12 & <2000)"
